debug: false
logging:
  level:
    org:
      hibernate:
        SQL: debug
  config: file:src/main/resources/logback-spring.xml
server:
  port: 9060

spring:
  liquibase:
    change-log: "classpath:db/master.xml"


  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:batchjobs;DB_CLOSE_DELAY=-1
    data-username: sa
    data-password:
  application:
    name: batchapplication
  profiles:
    active: uat
